services:
  - type: web
    name: react-portfolio
    env: node
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
